<?php
/** @package Rfc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AlunoMap.php");

/**
 * AlunoDAO provides object-oriented access to the aluno table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Rfc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AlunoDAO extends Phreezable
{
	/** @var int */
	public $Idaluno;

	/** @var string */
	public $Matricula;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Senha;

	/** @var int */
	public $Turma;

	/** @var string */
	public $Imagem;

	/** @var int */
	public $Condicao;


	/**
	 * Returns the foreign object based on the value of Turma
	 * @return Turma
	 */
	public function GetTurma()
	{
		return $this->_phreezer->GetManyToOne($this, "aluno_ibfk_1");
	}


}
?>