<?php
/** @package Rfc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TurmaMap.php");

/**
 * TurmaDAO provides object-oriented access to the turma table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Rfc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TurmaDAO extends Phreezable
{
	/** @var int */
	public $Idturma;

	/** @var string */
	public $Nometurma;

	/** @var int */
	public $Turno;


	/**
	 * Returns a dataset of Aluno objects with matching Turma
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAlunos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "aluno_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Turno
	 * @return Turno
	 */
	public function GetTurno()
	{
		return $this->_phreezer->GetManyToOne($this, "turma_ibfk_1");
	}


}
?>