<?php
/** @package Rfc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FichaMap.php");

/**
 * FichaDAO provides object-oriented access to the ficha table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Rfc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FichaDAO extends Phreezable
{
	/** @var int */
	public $Idficha;

	/** @var date */
	public $DataDasFichas;

	/** @var int */
	public $FichasMinimasDoDia;

	/** @var int */
	public $Cardapio;



}
?>