<?php
/** @package Rfc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TurnoMap.php");

/**
 * TurnoDAO provides object-oriented access to the turno table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Rfc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TurnoDAO extends Phreezable
{
	/** @var int */
	public $Idturno;

	/** @var int */
	public $Horario;

	/** @var int */
	public $Dias;


	/**
	 * Returns a dataset of Turma objects with matching Turno
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTurmas($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "turma_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Dias
	 * @return Semana
	 */
	public function GetDiasSemana()
	{
		return $this->_phreezer->GetManyToOne($this, "turno_ibfk_1");
	}


}
?>